baseURL = "http://blog.immport.org/"
languageCode = "en-us"
title = "ImmPort Blog"
theme = "hugo-bootstrap"


[params]
  DateForm = "Mon, Jan 1, 2018"
  Description = "ImmPort Blog"
  Author = "ImmPort Dev Team"
  email = "BISC_Helpdesk@niaid.nih.gov" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 6 #Number of post summaries to show on front page, comment out to allow default(4)

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -200
[[menu.footer]]
    name = "DISCLAIMER"
    weight = -110
    identifier = "disclaimer"
    url = "/page/disclaimer/"
[[menu.footer]]
    name = "LICENSE"
    weight = -120
    identifier = "license"
    url = "/page/license/"
